config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  resources :users  do
    resource :profile, only: [:show], controller: 'profiles'
  end

  resource :profile, only: %i[show edit update], controller: 'profiles'

  resources :rooms do
    resources :direct_messages, only: [:create]
    member do
      post 'clear_notification'
    end
  end
  
  resources :password_resets, only: %i[new create edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'oauth/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  get 'home', to: 'action_selection#index', as: :home

  resources :questions, only: [:index, :show] do
    collection do
      get 'subject'
      get 'year'
      get 'random'
      get 'next_random'
    end
    member do
      post 'answer'
    end
    resources :memos, only: [:create, :update]
  end

  get 'show_subject/:subject', to: 'questions#show_subject', as: :show_subject_questions
  get 'show_year/:year', to: 'questions#show_year', as: :show_year_questions

  resources :notebooks do
    resources :pages do
      member do
        patch 'save_content'
        post 'upload_image'
      end
    end
  end

  resources :wordbooks do
    member do
      get 'card'
    end
    resources :words
  end
  
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'history', to: 'posts#history', as: 'history'
    end
  end

  resources :diaries do
    collection do
      get 'calendar'
      get 'titles', to: 'diaries#index', as: 'titles'
    end
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options
  has_many :image_questions, dependent: :destroy
  has_many :answers
  has_many :question_correct_answers
  has_many :correct_answers, through: :question_correct_answers, source: :option
  has_many :memos, dependent: :destroy

  def correct_option_positions
    options.where(id: question_correct_answers.pluck(:correct_answer)).pluck(:position)
  end

  def correct_answer?(user_selected_option_ids)
    user_selected_positions = options.where(id: user_selected_option_ids).pluck(:position)
    correct_positions = question_correct_answers.pluck(:correct_answer)
    user_selected_positions.sort == correct_positions.sort
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def show
    @question = Question.includes(:options).find(params[:id])
    @image_questions = ImageQuestion.where(question_id: @question.id)
    @answer = Answer.new
    @memo = Memo.where(user_id: current_user.id, question_id: @question.id).first
    @is_random_question = session[:last_random_question_id] == @question.id
    
    if params[:retain_selection] == "true"
      @selected_option_ids = session[:selected_option_ids] || []
    else
      session.delete(:selected_option_ids)
      @selected_option_ids = []
    end

    questions_list = session[:questions_list] || []
    current_index = questions_list.find_index(@question.id)
  
    if current_index && current_index + 1 < questions_list.size
      @next_question_id = questions_list[current_index + 1]
    else
      @next_question_id = nil
    end

    session[:last_random_question_id] = @question.id if params[:from] == 'random'
  end

  def subject
    @subjects = SUBJECTS
  end

  def show_subject
    @subject = params[:subject]
    unless SUBJECTS.include?(@subject)
      redirect_to(root_path, alert: '無効な分野が指定されました。') and return
    end
    @questions = Question.where(subject: @subject).order(year: :desc, id: :asc)
    session[:questions_list] = @questions.map(&:id)
  end

  def answer
    @question = Question.find(params[:id])
    selected_option_ids = params[:answer].try(:[], :selected_option_ids) || []
    selected_options = selected_option_ids.map(&:to_i)
    
    if selected_options.empty?
      flash[:alert] = "選択肢を選んでください。"
      redirect_to question_path(@question) and return
    end

    is_correct = @question.correct_answer?(selected_options)
    flash[is_correct ? :notice : :alert] = is_correct ? "正解です！" : "不正解です。"
    session[:selected_option_ids] = selected_option_ids
    
    redirect_params = { retain_selection: "true" }
    redirect_params[:from] = 'random' if session[:last_random_question_id] == @question.id
    redirect_to question_path(@question, redirect_params)
  end

  def year
    @years = YEARS
  end

  def show_year
    @year = params[:year]
    unless YEARS.include?(@year)
      redirect_to(root_path, alert: '無効な分野が指定されました。') and return
    end
    @questions = Question.where(year: @year).order(:id)
    session[:questions_list] = @questions.map(&:id)
  end

  def random
    @question = Question.order(Arel.sql('RANDOM()')).first
    session[:last_random_question_id] = @question.id
    @image_questions = ImageQuestion.where(question_id: @question.id)
  end

  def next_random
    session[:last_random_question_id] = nil
    session.delete(:selected_option_ids) 
    redirect_to action: :random
  end
end

app/views/questions/field.html.erb
<div class="flex flex-col items-center justify-center h-screen space-y-4">
  <h1 class="text-2xl font-bold">分野選択</h1>
  <% @fields.each do |field| %>
    <%= link_to field, "#", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/questions/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center justify-center min-h-screen space-y-4 font-yuji-syuku p-4 sm:p-6 lg:p-8">
  <h1 class="text-3xl font-bold mb-4">過去問</h1>
  <div class="w-full max-w-3xl bg-white rounded-lg shadow-lg p-6">
    <p class="text-center text-gray-600 text-lg font-semibold mb-4">問題の解き方を選んでください。</p>
    <div class="border-t border-gray-300 my-4"></div>

    <div class="flex flex-wrap justify-around mt-8 gap-4">
      <div class="flex justify-center w-full sm:w-auto">
        <%= link_to '分野', subject_questions_path, data: { turbo: false }, class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
      </div>
      <div class="flex justify-center w-full sm:w-auto">
        <%= link_to '年代', year_questions_path, data: { turbo: false }, class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
      </div>
      <div class="flex justify-center w-full sm:w-auto">
        <%= link_to 'ランダム', random_questions_path, class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
      </div>
    </div>
  </div>
</div>

app/views/questions/random.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex justify-end p-4 space-x-2 font-yuji-syuku">
  <% if params[:from] == 'subject' %>
    <%= link_to '問題一覧', show_subject_questions_path(subject: @question.subject), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover" %>
  <% elsif params[:from] == 'year' %>
    <%= link_to '問題一覧', show_year_questions_path(year: @question.year), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover" %>
  <% else %>
    <%= link_to '問題一覧', questions_path, class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover" %>
  <% end %>
  <%= link_to '解き方選択', questions_path, class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover" %>
</div>

<div class="<%= @image_questions&.any? { |iq| iq.image_url.present? } ? 'flex flex-col justify-center items-center min-h-screen font-yuji-syuku space-y-4 w-full' : 'flex justify-center items-start min-h-screen mx-auto px-4 font-yuji-syuku w-full pt-8' %>">
  <% content_for :head do %>
    <meta name="turbo-visit-control" content="reload">
    <%= javascript_import_module_tag "toggle_memo" %>
  <% end %>

  <!-- 画像を含むコンテナ -->
  <% if @image_questions.any? { |iq| iq.image_url.present? } %>
    <div class="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4" style="width:90%; margin: auto;">
      <!-- 画像と質問の詳細を囲む枠 -->
      <div class="w-full md:w-1/2 border-2 border-gray-300 p-4 rounded-lg shadow-lg bg-custom-question">
        <!-- 画像 -->
        <div class="w-full flex justify-center items-center mb-4">
          <% @image_questions.each do |image_question| %>
            <% if image_question.image_url.present? %>
              <div class="bg-contain bg-center" style="background-image: url('<%= image_question.image_url %>'); background-repeat: no-repeat; width: 100%; height: 400px;">
                  <!-- 背景画像が表示 -->
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- 問題画面 -->
        <div class="w-full flex flex-col justify-center items-start text-xl text-left">
          <h2 class="mb-6 text-lg"><%= @question.question_text %></h2>
          <%= form_with model: @answer, url: answer_question_path(@question), local: true, data: { turbo: false } do |form| %>
            <% @question.options.order(:position).each do |option| %>
              <div class="field">
                <%= check_box_tag 'answer[selected_option_ids][]', option.id, @selected_option_ids&.include?(option.id.to_s), id: "selected_option_ids_#{option.position}" %>
                <%= label_tag "selected_option_ids_#{option.position}", option.option_text, class: "text-lg" %>
              </div>
            <% end %>
            <%= form.submit "Answer!", class: "btn bg-custom-home-button-green text-custom-home-text-green hover:bg-custom-home-button-hover-blue mt-8" %>
          <% end %>
        </div>
      </div>

      <!-- メモ -->
      <div class="w-full md:w-1/2 border-2 border-gray-300 p-4 rounded-lg shadow-lg bg-custom-memo">
        <% if @memo.present? %>
          <div class="flex items-center space-x-4">
            <button id="toggle-memo" class="btn bg-custom-memo-button hover:bg-custom-memo-button-hover text-custom-memo-text">メモを見る</button>
            <div class="relative max-w-xs">
              <p class="text-gray-700 text-sm bg-custom-home-green border border-gray-300 rounded-lg p-4 shadow-lg">
                メモを隠すボタンをクリックすると<br>
                編集内容が保存されます
              </p>
              <div class="absolute -left-2 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-gray-300"></div>
              <div class="absolute -left-1.5 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-custom-home-green"></div>
            </div>
            <% if @is_random_question %>
              <%= link_to '次の問題', next_random_questions_path, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text" %>
            <% elsif @next_question_id.present? %>
              <%= link_to '次の問題', question_path(@next_question_id), data: { turbo: false }, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text" %>
            <% else %>
              <p class="text-lg">これが最後の問題です。</p>
            <% end %>
          </div>
          <div id="content" style="display:none;">
            <div id="editable-memo"
                contenteditable="true"
                class="memo mt-2 p-4 border-2 border-custom-memo-content-box bg-white rounded-lg shadow-lg cursor-text hover:border-custom-memo-content-box-hover text-gray-700 text-lg"
                style="cursor: text;"
                data-question-id="<%= @question.id %>" 
                data-memo-id="<%= @memo.id %>">
              <%= raw @memo.content %>
            </div>
          </div>
        <% else %>
          <%= form_with(model: [ @question, @question.memos.build ], local: true, data: { turbo: false }) do |form| %>
            <div class="field">
              <%= form.label :content, "< 解説メモ >", class: "label text-lg text-custom-memo-text" %>
              <%= form.text_area :content, rows: 3, class: "textarea textarea-bordered border-custom-memo-content-box hover:border-custom-memo-content-box-hover text-lg bg-white w-full auto-resize", required: true %>
            </div>
            <%= form.submit "メモを保存", class: "btn bg-custom-memo-button hover:bg-custom-memo-button-hover text-custom-memo-text" %>
          <% end %>
          <%= link_to '次の問題', next_random_questions_path, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text mt-4" %>
        <% end %>
      </div>
    </div>
  <% else %>

    <!-- 画像がない場合のコンテナ -->
    <div class="flex flex-col md:flex-row w-full space-y-4 md:space-y-0 md:space-x-4 pt-4">
      <!-- 質問の詳細の枠 -->
      <div class="w-full md:w-1/2 border-2 border-gray-300 p-4 rounded-lg shadow-lg bg-custom-question">
        <h2 class="mb-6 text-lg"><%= @question.question_text %></h2>
        <%= form_with model: @answer, url: answer_question_path(@question), local: true, data: { turbo: false } do |form| %>
          <% @question.options.order(:position).each do |option| %>
            <div class="field">
              <%= check_box_tag 'answer[selected_option_ids][]', option.id, @selected_option_ids&.include?(option.id.to_s), id: "selected_option_ids_#{option.position}" %>
              <%= label_tag "selected_option_ids_#{option.position}", option.option_text, class: "text-lg" %>
            </div>
          <% end %>
          <%= form.submit "Answer!", class: "btn bg-custom-home-button-green text-custom-home-text-green hover:bg-custom-home-button-hover-blue mt-8" %>
        <% end %>
      </div>

      <!-- メモz -->
      <div class="w-full md:w-1/2 border-2 border-gray-300 p-4 rounded-lg shadow-lg bg-custom-memo">
        <% if @memo.present? %>
          <div class="flex items-center space-x-4 mt-4">
            <button id="toggle-memo" class="btn bg-custom-memo-button hover:bg-custom-memo-button-hover text-custom-memo-text">メモを見る</button>
            <div class="relative max-w-xs">
              <p class="text-gray-700 text-sm bg-custom-home-green border border-gray-300 rounded-lg p-4 shadow-lg">
                メモを隠すボタンをクリックすると<br>
                編集内容が保存されます
              </p>
              <div class="absolute -left-2 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-gray-300"></div>
              <div class="absolute -left-1.5 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-custom-home-green"></div>
            </div>

            <% if @is_random_question %>
              <%= link_to '次の問題', next_random_questions_path, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text" %>
            <% elsif @next_question_id.present? %>
              <%= link_to '次の問題', question_path(@next_question_id), data: { turbo: false }, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text" %>
            <% else %>
              <p class="text-lg">これが最後の問題です。</p>
            <% end %>
          </div>
          <div id="content" style="display:none;">
            <div id="editable-memo"
                contenteditable="true"
                class="memo mt-2 p-4 border-2 border-custom-memo-content-box bg-white rounded-lg shadow-lg cursor-text hover:border-custom-memo-content-box-hover text-gray-700 text-lg"
                style="cursor: text;"
                data-question-id="<%= @question.id %>" 
                data-memo-id="<%= @memo.id %>">
              <%= raw @memo.content %>
            </div>
          </div>
        <% else %>
          <%= form_with(model: [ @question, @question.memos.build ], local: true, data: { turbo: false }) do |form| %>
            <div class="field">
              <%= form.label :content, "< 解説メモ >", class: "label text-lg text-custom-memo-text" %>
              <%= form.text_area :content, rows: 3, class: "textarea textarea-bordered border-custom-memo-content-box hover:border-custom-memo-content-box-hover text-lg bg-white w-full auto-resize", required: true %>
            </div>
            <%= form.submit "メモを保存", class: "btn bg-custom-memo-button hover:bg-custom-memo-button-hover text-custom-memo-text" %>
          <% end %>
          <%= link_to '次の問題', next_random_questions_path, class: "bg-custom-question-next-button btn hover:bg-custom-question-next-button-hover text-custom-memo-text mt-4" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/show_subject.html.erb
<% content_for(:title, t('.title')) %>
<div class="font-yuji-syuku pt-16">
  <h1 class="text-3xl font-bold text-center mt-4 mb-6"><%= @subject %>の問題</h1>
  <div class="mx-auto max-w-4xl px-4">
    <% @questions.each do |question| %>
      <div class="mb-4">
        <%= link_to question.question_text, question_path(question, from: 'subject'), class: "block p-4 bg-white rounded shadow-lg hover:shadow-xl" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show_year.html.erb
<% content_for(:title, t('.title')) %>
<div class="font-yuji-syuku pt-16">
  <h1 class="text-3xl font-bold text-center mt-4 mb-6"><%= @year %>の問題</h1>
  <div class="mx-auto max-w-4xl px-4">
    <% @questions.each do |question| %>
      <div class="mb-4">
        <%= link_to question.question_text, question_path(question, from: 'year'), class: "block p-4 bg-white rounded shadow-lg hover:shadow-xl" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/subject.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center justify-center min-h-screen space-y-4 font-yuji-syuku p-4">
  <h1 class="text-3xl font-bold mb-4">分野選択</h1>
  <div class="w-full max-w-3xl bg-white rounded-lg shadow-lg p-6">
    <p class="text-center text-gray-600 text-lg font-semibold mb-4">
      臨床化学・生理学・病理学は<br>
      特に出題数が多いので早めに学習を始めておくと良いです。
    </p>
    <div class="border-t border-gray-300 my-4"></div>

    <div class="flex flex-wrap justify-around mt-8">
      <!-- 左 -->
      <div class="flex flex-col space-y-4 w-full sm:w-1/3">
        <% @subjects[0..2].each do |subject| %>
          <div class="flex justify-center">
            <%= link_to subject, show_subject_questions_path(subject: subject), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
          </div>
        <% end %>
      </div>

      <!-- 中央 -->
      <div class="flex flex-col space-y-4 w-full sm:w-1/3">
        <% @subjects[3..7].each do |subject| %>
          <div class="flex justify-center">
            <%= link_to subject, show_subject_questions_path(subject: subject), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
          </div>
        <% end %>
      </div>

      <!-- 右 -->
      <div class="flex flex-col space-y-4 w-full sm:w-1/3">
        <% @subjects[8..9].each do |subject| %>
          <div class="flex justify-center">
            <%= link_to subject, show_subject_questions_path(subject: subject), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/year.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center justify-center min-h-screen space-y-4 font-yuji-syuku p-4 sm:p-6 lg:p-8">
  <h1 class="text-3xl font-bold mb-4">年代選択</h1>
  <div class="w-full max-w-3xl bg-white rounded-lg shadow-lg p-6">
    <p class="text-center text-gray-600 text-lg font-semibold mb-4">どの問題を解きますか。</p>
    <div class="border-t border-gray-300 my-4"></div>

    <div class="flex flex-wrap justify-around mt-8 gap-4">
      <% @years.each do |year| %>
        <div class="w-full sm:w-auto flex justify-center">
          <%= link_to year, show_year_questions_path(year: year), class: "btn bg-custom-question-button-blue text-custom-home-text-green hover:bg-custom-question-button-blue-hover text-base w-full sm:w-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>