config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  resources :users  do
    resource :profile, only: [:show], controller: 'profiles'
  end

  resource :profile, only: %i[show edit update], controller: 'profiles'

  resources :rooms do
    resources :direct_messages, only: [:create]
    member do
      post 'clear_notification'
    end
  end
  
  resources :password_resets, only: %i[new create edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'oauth/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  get 'home', to: 'action_selection#index', as: :home

  resources :questions, only: [:index, :show] do
    collection do
      get 'subject'
      get 'year'
      get 'random'
      get 'next_random'
    end
    member do
      post 'answer'
    end
    resources :memos, only: [:create, :update]
  end

  get 'show_subject/:subject', to: 'questions#show_subject', as: :show_subject_questions
  get 'show_year/:year', to: 'questions#show_year', as: :show_year_questions

  resources :notebooks do
    resources :pages do
      member do
        patch 'save_content'
        post 'upload_image'
      end
    end
  end

  resources :wordbooks do
    member do
      get 'card'
    end
    resources :words
  end
  
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'history', to: 'posts#history', as: 'history'
    end
  end

  resources :diaries do
    collection do
      get 'calendar'
      get 'titles', to: 'diaries#index', as: 'titles'
    end
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div id="flash" data-turbo-cache="false">
  <% flash.each do |type, message| %>
    <div class="<%= flash_class(type) %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="font-yuji-syuku bg-custom-header-footer text-custom-color">
  <div class="container mx-auto px-4 py-6">
    <div class="flex justify-between items-center">
      <div class="flex items-center">
        <%= link_to '利用規約', terms_path, class: 'text-sm px-4 hover:underline' %>
        <%= link_to 'プライバシーポリシー', privacy_path, class: 'text-sm px-4 hover:underline' %>
        <%= link_to 'お問い合わせ', "https://docs.google.com/forms/d/e/1FAIpQLSe271KHCBINBVlcc8-3obl2CO5sM9RTSLOCT--I3luNsj4blQ/viewform?usp=sf_link", class: 'text-sm px-4 hover:underline' %>
      </div>
      <div class="text-sm">
        © 2024 MT*Life
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-custom-header-footer text-custom-color font-yuji-syuku z-50">
  <div class="container mx-auto">
    <div class="flex justify-between items-center py-2">
      <div class="flex justify-start items-center">
        <%= link_to image_tag('logo.png', alt: 'MTLife', class: 'h-16 w-auto'), root_path %>
      </div>
      <div class="flex items-center">
      <% if logged_in? %>
        <div class="flex items-center">
          <%= link_to 'Profile', profile_path, class: 'text-sm font-medium text-gray-700 px-4 hover:text-gray-900' %>
          <%= link_to 'Logout', logout_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" }, class: 'text-sm font-medium text-gray-700 px-4 hover:text-gray-900' %>
          <% end %>
        </div>
    </div>
  </div>
</header>