config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  resources :users  do
    resource :profile, only: [:show], controller: 'profiles'
  end

  resource :profile, only: %i[show edit update], controller: 'profiles'

  resources :rooms do
    resources :direct_messages, only: [:create]
    member do
      post 'clear_notification'
    end
  end
  
  resources :password_resets, only: %i[new create edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'oauth/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  get 'home', to: 'action_selection#index', as: :home

  resources :questions, only: [:index, :show] do
    collection do
      get 'subject'
      get 'year'
      get 'random'
      get 'next_random'
    end
    member do
      post 'answer'
    end
    resources :memos, only: [:create, :update]
  end

  get 'show_subject/:subject', to: 'questions#show_subject', as: :show_subject_questions
  get 'show_year/:year', to: 'questions#show_year', as: :show_year_questions

  resources :notebooks do
    resources :pages do
      member do
        patch 'save_content'
        post 'upload_image'
      end
    end
  end

  resources :wordbooks do
    member do
      get 'card'
    end
    resources :words
  end
  
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'history', to: 'posts#history', as: 'history'
    end
  end

  resources :diaries do
    collection do
      get 'calendar'
      get 'titles', to: 'diaries#index', as: 'titles'
    end
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :post_content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.includes(:user).order(created_at: :desc)
    @has_post_history = current_user.posts.exists?
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿が完了しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿が削除されました。"
  end

  def history
    @posts = current_user.posts.order(created_at: :desc)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user
    redirect_to posts_path, alert: "権限がありません。" unless @post.user == current_user
  end
  
  def post_params
    params.require(:post).permit(:post_content)
  end
end

app/views/posts/edit.html.erb
<%= content_for :title, t('.title') %>
<div class="container mx-auto p-3 font-yuji-syuku">
  <h1 class="text-3xl font-bold text-center my-8">投稿編集</h1>
  <div class="max-w-2xl mx-auto bg-white rounded-lg shadow-md overflow-hidden">
    <%= form_with(model: @post, local: true) do |form| %>
      <div class="p-6">
        <div class="mb-4">
          <%= form.label :post_content, "投稿内容", class: "block text-gray-700 font-bold mb-2" %>
          <%= form.text_area :post_content, rows: 10, class: "bg-custom-post form-textarea mt-1 block w-full" %>
        </div>
        <div class="flex justify-end space-x-4">
          <%= form.submit '更新', class: "bg-custom-post-edit hover:bg-custom-post-edit-hover text-custom-text3 rounded-lg py-2 px-4" %>
          <%= link_to 'キャンセル', history_posts_path, class: "bg-custom-button-4 hover:bg-hover-button-4 rounded-lg py-2 px-4" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/history.html.erb
<%= content_for :title, t('.title') %>
<div class="container mx-auto p-3 font-yuji-syuku">
  <h1 class="text-3xl font-bold text-center my-8">投稿履歴</h1>
  <div class="flex justify-start mb-10 gap-10">
    <%= link_to '📝', new_post_path, data: { turbo: false }, class: "bg-custom-post-edit hover:bg-custom-post-edit-hover text-custom-text3 rounded-lg py-2 px-6 flex items-center justify-center text-3xl" %>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
    <% @posts.each do |post| %>
      <div class="bg-white rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transition-shadow duration-300 ease-in-out">
        <div class="p-6">
          <div class="flex items-center mb-4">
            <%= link_to user_profile_path(post.user) do %>  
              <% if post.user.avatar? %>
                <img src="<%= post.user.avatar.url %>" alt="<%= post.user.name %>のアバター" class="w-16 h-16 rounded-full mr-4">
              <% else %>
                <img src="<%= asset_path('avatar.png') %>" alt="デフォルトアバター" class="w-16 h-16 rounded-full mr-4">
              <% end %>
              <strong class="text-lg"><%= post.user.name %></strong>
            <% end %>
          </div>
          <div class="border-t border-gray-300 my-5"></div>
          <div class="bg-custom-post p-2 rounded-lg max-h-32 overflow-y-auto overflow-x-hidden h-32">
            <p class="text-gray-800 text-base mb-2  whitespace-pre-line"><%= post.post_content %></p>
          </div>
          <span class="text-gray-600 text-sm block">投稿日: <%= post.created_at.strftime("%Y/%m/%d") %></span>
          <div class="mt-4 flex justify-end space-x-2">
            <%= link_to '編集', edit_post_path(post), class: "bg-custom-post-edit hover:bg-custom-post-edit-hover text-custom-text3 rounded-lg py-2 px-4" %>
            <%= link_to '削除', post_path(post), method: :delete, data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: "bg-custom-post-delete hover:bg-custom-post-delete-hover text-custom-text4 rounded-lg py-2 px-4 rounded" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= content_for :title, t('.title') %>
<div class="container mx-auto p-3 font-yuji-syuku">
  <h1 class="text-3xl font-bold text-center my-8">投稿一覧</h1>
  <div class="flex justify-start mb-10 gap-10">
    <div class="flex items-center space-x-10">
      <%= link_to '📝', new_post_path, data: { turbo: false }, class: "bg-custom-post-edit hover:bg-custom-post-edit-hover text-custom-text3 rounded-lg py-2 px-6 flex items-center justify-center text-3xl" %>
      <% if @has_post_history %>
        <%= link_to '履歴', history_posts_path, data: { turbo: false }, class: "bg-custom-button-purple px-4 py-3 flex items-center justify-center rounded-lg hover:bg-custom-hover-lightblue text-custom-text-darkreddishpurple text-lg" %>
      <% end %>
      <div class="relative max-w-xs">
        <p class="text-gray-700 text-sm bg-custom-home-green border border-gray-300 rounded-lg p-4 shadow-lg">
          ユーザーをクリックするとメッセージを送ることができます。<br>
          次からは、ホームの"連絡"画面から<br>
          いつでもメッセージのやり取りが可能です。
        </p>
        <div class="absolute -left-2 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-gray-300"></div>
        <div class="absolute -left-1.5 top-1/2 transform -translate-y-1/2 w-0 h-0 border-t-8 border-t-transparent border-b-8 border-b-transparent border-r-8 border-custom-home-green"></div>
      </div>
    </div>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
    <% @posts.each do |post| %>
      <div class="bg-white rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transition-shadow duration-300 ease-in-out">
        <div class="p-6">
          <div class="flex items-center mb-4">
            <%= link_to user_profile_path(post.user) do %>  
              <% if post.user.avatar? %>
                <img src="<%= post.user.avatar.url %>" alt="<%= post.user.name %>のアバター" class="w-16 h-16 rounded-full mr-4">
              <% else %>
                <img src="<%= asset_path('avatar.png') %>" alt="デフォルトアバター" class="w-16 h-16 rounded-full mr-4">
              <% end %>
              <strong class="text-lg"><%= post.user.name %></strong>
            <% end %>
          </div>
          <div class="border-t border-gray-300 my-5"></div>
          <div class="bg-custom-post p-2 rounded-lg max-h-32 overflow-y-auto overflow-x-hidden h-32">
            <p class="text-gray-800 text-base mb-2  whitespace-pre-line"><%= post.post_content %></p>
          </div>
          <span class="text-gray-600 text-sm block">投稿日: <%= post.created_at.strftime("%Y/%m/%d") %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= content_for :title, t('.title') %>
<div class="absolute inset-0 flex items-center justify-center">
  <div class="container mx-auto mt-8 font-yuji-syuku">
    <h1 class="text-2xl font-bold text-center mb-6">新規投稿</h1>
    <%= form_with model: @post, local: true do |form| %>
      <div class="max-w-xl mx-auto shadow-lg rounded-lg p-6 bg-white">
        <div class="mb-4">
          <%= form.label :post_content, "内容", class: "block text-sm font-medium text-gray-700 mb-2" %>
          <%= form.text_area :post_content, required: true, class: "bg-custom-post form-textarea mt-1 block textarea textarea-bordered h-48 w-full" %>
        </div>
        <div class="flex justify-end mt-4">
          <%= form.submit "📝投稿", class: "bg-custom-post-edit hover:bg-custom-post-edit-hover text-custom-text3 flex items-center justify-center btn text-base" %>
        </div>
      </div>
    <% end %>
  </div>
</div>